# Generated by Django 5.0 on 2024-12-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_usermodel_email_usermodel_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=150)),
                ('seller', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
