# Generated by Django 5.0 on 2024-12-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_productmodel_stocks_ordermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='stocks',
            field=models.IntegerField(default=100),
        ),
    ]
